### ISSUE TITLE
'delete' in the service part passing parameters

### ISSUE THREAD

**Issue by thanit456** [2110423-2019-2/sec1_TerkyCompany-BackEnd#5]
<img width="1280" alt="Screen Shot 2563-02-15 at 10 24 51" src="https://user-images.githubusercontent.com/35522239/74581062-81119000-4fdd-11ea-9d06-70b3f60cdc2a.png">

I am not sure that I can do like above or I have to create an object then passing by it.

Please help me.

**Comment by thanit456** [comment]
'workshop' is a foreign key  that I create via relation.

**Comment by UtopiaBeam** [comment]
Can you show me your entity declaration?

**Comment by thanit456** [comment]
@UtopiaBeam  
<img width="1280" alt="Screen Shot 2563-02-15 at 18 21 09" src="https://user-images.githubusercontent.com/35522239/74586995-f3a35f80-501f-11ea-93fd-aa547875a91e.png">
<img width="1280" alt="Screen Shot 2563-02-15 at 18 21 35" src="https://user-images.githubusercontent.com/35522239/74587009-19c8ff80-5020-11ea-8f87-b8c18880a9e8.png">
<img width="1280" alt="Screen Shot 2563-02-15 at 18 22 29" src="https://user-images.githubusercontent.com/35522239/74587017-264d5800-5020-11ea-90a4-7342afdcedd2.png">

**Comment by UtopiaBeam** [comment]
You could either pass the `workshop` object (maybe find that workshop by ID beforehand) or just pass filters like `{ workshop: { id } }` since `id` is a field in `workshop`.

Tell me if you still face some problems.

**Comment by thanit456** [comment]
Hooray! This issue's already been solved.Thank you for your support
